version: '3.8'

services:
  # FastAPI Application
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: plytix-api
    ports:
      - "8001:8000"  # Use port 8001 instead of 8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/integration_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./field_mappings.json:/app/field_mappings.json
    networks:
      - plytix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Celery Worker
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: plytix-worker
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/integration_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./field_mappings.json:/app/field_mappings.json
    networks:
      - plytix-network
    restart: unless-stopped

  # Celery Beat Scheduler
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: plytix-beat
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/integration_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - plytix-network
    restart: unless-stopped
    command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=info"]

  # Celery Flower Monitoring
  flower:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: plytix-flower
    ports:
      - "5556:5555"  # Use port 5556 instead of 5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - plytix-network
    restart: unless-stopped
    command: ["celery", "-A", "app.tasks.celery_app", "flower", "--port=5555", "--basic-auth=admin:admin"]

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: plytix-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integration_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"  # Use port 5433 instead of 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - plytix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d integration_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    container_name: plytix-redis
    ports:
      - "6380:6379"  # Use port 6380 instead of 6379
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - plytix-network
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  plytix-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local